### ISSUE TITLE
Build error with Xcode 12

### ISSUE THREAD

**Issue by Francesco-Voto** [Appboy/appboy-react-sdk#104] opened 2021-03-15 10:03 UTC
After Upgrading to Xcode 12 we got some problems to build the package.

Apparently the problem is the `dependency` inside the `react-native-appboy-sdk.podspec `

Changing `s.dependency 'React'` to `s.dependency 'React-Core'` seems to fix the problem.
 Is this the right solution or you have some other fix?

Thank you

**Comment by Bucimis** [comment] 2021-03-15 18:15
@Francesco-Voto can you post more information about the errors you're seeing?

**Comment by Francesco-Voto** [comment] 2021-03-16 10:10
Sure!

Whe we try to build it we got 
<img width="825" alt="Schermata 2021-03-16 alle 11 09 35" src="https://user-images.githubusercontent.com/8778613/111292130-27e4b780-8648-11eb-81d8-be7d124a11da.png">

**Comment by Bucimis** [comment] 2021-03-18 00:15
@Francesco-Voto I wasn't able to reproduce this using Xcode 12.4. I would recommend:
1. removing react-native-appboy-sdk from your node_modules and re-installing
2. removing your `Pods` directory and rerunning `pod install`

A few questions:
1. What version of react native are you on?
2. Do you see any warnings about autolinking?

Fwiw it looks like the missing symbol is from `RCTEventEmitter`, which is part of `React`. I would make sure wherever you're compiling React, that you aren't excluding architectures by overwriting or changing build settings

**Comment by jlo1** [comment] 2021-07-12 18:43
Related: https://github.com/facebook/react-native/issues/29633

Switching from `s.dependency 'React'` to `s.dependency 'React-Core'` is needed to get off the Legacy Build system.

**Comment by Bucimis** [comment] 2021-07-12 20:13
Thanks @jlo1 - I agree, that looks correct. I've filed an internal issue to investigate.

**Comment by hokstuff** [comment] 2023-01-04 20:50
Hi @Francesco-Voto @jlo1,

This issue should be addressed in version 1.40.0 of the release from [this attached PR](https://github.com/Appboy/appboy-react-sdk/pull/175). Feel free to open a new issue if you are still experiencing problems with that update or when testing on Xcode 13.

Thanks!

**Closed by hokstuff** 2023-01-04 20:50 UTC
