### ISSUE TITLE
Android Issue: Warning: None of the selected users have matching push tokens for Android Push.

### ISSUE THREAD

**Issue by shethabhish** [Appboy/appboy-react-sdk#131] opened 2021-11-11 17:58 UTC
I'm not sure what happened, I followed everything that was required to integrate Android Push, it worked a couple of weeks back, but not now. When I try to send a Push to an ID, it says: Warning: None of the selected users have matching push tokens for Android Push. The below are push settings of the user

![Screen Shot 2021-11-11 at 9 56 33 AM](https://user-images.githubusercontent.com/20106435/141346441-bb89ab0a-df3c-4fdc-ad00-c83c31043895.png)

Also I recall couple of weeks back there wasn't this SDK Authentication
![Screen Shot 2021-11-11 at 9 57 45 AM](https://user-images.githubusercontent.com/20106435/141346316-3191a227-e0b8-433c-8c13-6e7ba0c92f1f.png)
 Could this be the cause should we configure this part to make it work?

**Comment by wesleyorbin** [comment] 2021-11-12 20:22
Closing as this is a duplicate of https://github.com/Appboy/appboy-android-sdk/issues/205

**Closed by wesleyorbin** 2021-11-12 20:22 UTC

**Comment by AbdulmalekAlshugaa** [comment] 2024-07-22 10:00
@shethabhish did you managed to fix it , Braze documentation seems missing some of hiding steps or what .
