### ISSUE TITLE
News Feed doesn't close after pressing a deeplink

### ISSUE THREAD

**Issue by zevmo** [Appboy/appboy-react-sdk#14] opened 2017-05-19 17:22 UTC
If you add a deeplink to a news feed item, and that deeplink is internal to the same app, the deeplink will work... but the news feed modal didn't automatically close showing what happened behind it.

**Comment by tiffanylu** [comment] 2017-05-19 17:37
Hi @zevmo,

Thanks for opening an issue. Are you seeing this behavior on iOS, Android or both platforms?

Best,
Tiff

**Comment by zevmo** [comment] 2017-05-19 20:17
Confirmed that this only appears on iOS. Android works.

**Comment by tiffanylu** [comment] 2017-05-19 22:03
Hi @zevmo,

The expected behavior for both platforms is that clicking on News Feed card with a deep link will open the link, *without* automatically closing the News Feed. In this light, Android is actually the platform with unexpected behavior here, and I am able to reproduce this on our sample app.

We'll be taking a closer look at this and hope to get back to you next week. Please note that any potential fixes will likely standardize behavior to *not* automatically close the News Feed. If you have any thoughts or feedback on this, please let us know.

Best,
Tiff

**Comment by zevmo** [comment] 2017-05-22 19:40
@tiffanylu so the expected behavior is that when a person taps on the link in a news feed card, iOS or Android, the internal deep link opens behind the news feed modal? As there isn't any way for the user to know that it did open as they expected, or that they need to close the modal to get to that link, isn't that a bad UX?

**Comment by tiffanylu** [comment] 2017-05-22 19:43
Hi @zevmo,

We've done some more investigation and have a few clarifications about expected behavior. On Android, if a task is already running for the activity you start with an Appboy deep link, that task is brought to the foreground and cleared to its root state. You can see the code for this in [UriAction.java](https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/com/appboy/ui/actions/UriAction.java#L105), and relevant documentation [here](https://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_CLEAR_TOP). For example, if you launch the News Feed from your MainActivity and then deep link back to your MainActivity, your MainActivity will be brought to the foreground and any child activities (including the News Feed) will be cleared. 

On iOS, the way that deep links are handled is entirely up to the developer, who is in charge of handling the view controller hierarchy themselves (i.e., in [`application:openURL:options:`](https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623112-application?language=objc)). Therefore, the News Feed is not automatically closed when navigating to an existing view controller. Since our iOS SDK cannot know the view controller hierarchy of the apps that use it, it is up to developers to implement this logic themselves.

Hope that helps provide some context! Please let us know if you have any other questions.

Best,
Tiff

**Comment by tiffanylu** [comment] 2017-05-22 19:49
Just to clarify — after clicking on a News Feed card with a deep link, users should be taken to the correct screen in your application. Could you help us understand what you're seeing instead? A video could prove helpful here, as we might be misunderstanding the behavior you're observing.

Thanks!

**Comment by zevmo** [comment] 2017-05-22 19:55
Essentially, the behavior is as correct on Android for us. 

In iOS, once you tap on a link in the news feed, the link does, in fact, open behind the news feed modal, but it requires you to close the feed to see it.

**Comment by tiffanylu** [comment] 2017-05-22 21:27
Hi @zevmo,

Thanks for clarifying! We're going to strategize around a solution here and get back to you as soon as we have more concrete details. Any context around necessary timelines will help us prioritize accordingly.

Best,
Tiff

**Comment by tiffanylu** [comment] 2017-05-26 14:43
Hi @zevmo,

Our proposed solution here is to add a `dismissNewsFeed()` to the React Native bridge, which will dismiss the News Feed on iOS and be a no-op on Android. You can then update your `url` event handler to call `dismissNewsFeed()` if your application is handling a deep link. The `dismissNewsFeed()` method would also be a no-op on iOS if there is no current News Feed instance being presented. 

Please let us know if you have any feedback or if you think this approach would work for your use case. If you're interested in testing the solution in your application, we'd be happy to send you a private version of the React Native bridge via email.

Best,
Tiff

**Comment by tiffanylu** [comment] 2017-05-31 17:46
Hi @zevmo,

Feel free to e-mail me directly at tiffany@appboy.com if you're interested in testing a private version of the React Native bridge with the `dismissNewsFeed()` implementation. We want to make sure that any solution we release will suit your use case.

Best,
Tiff

**Comment by zevmo** [comment] 2017-08-22 16:33
Will do!

**Comment by tiffanylu** [comment] 2017-09-07 19:54
Hi @zevmo! Have you gotten a chance to test out the private version we sent you? We'd love to be able to iterate on our solution per your feedback and close out this issue. 

Best,
Tiff

**Comment by zevmo** [comment] 2017-09-13 17:36
I'm taking a look... let you know. Thanks!

**Comment by Bucimis** [comment] 2018-02-22 22:13
HI @zevmo, let us know if this is still an open issue for you or if you've found a workaround. Feel free to direct future communication to jared@braze.com. Thanks!

**Comment by Bucimis** [comment] 2018-04-24 23:00
closing - please reach our per https://github.com/Appboy/appboy-react-sdk/issues/14#issuecomment-367840448 if this issue is still relevant. thanks!

**Closed by Bucimis** 2018-04-24 23:00 UTC

**Comment by ishaq-aym** [comment] 2019-02-18 18:21
ReactAppboy.dismissNewsFeed() is undefined @Bucimis @tiffanylu

**Comment by Bucimis** [comment] 2019-02-18 21:22
@ishaq-aym we haven't added `dismissNewsFeed` functionality to our public API. Could you describe your usecase/issue in more detail?

**Comment by ishaq-aym** [comment] 2019-02-19 05:38
like i have a news Feed list . user click on any newsFeed will go to the specific product/page using deepLink. but the modal of newsFeed not automatic close when the user click on any newsFeed. i want to close the modal when the user click on any newsFeed   @Bucimis

**Comment by Bucimis** [comment] 2019-02-20 04:37
@ishaq-aym gotcha, thanks for the context. That use-case is currently unsupported from Javascript but we'll investigate adding a `dismissFeed` method in a future release. In the meantime, if you are able to access native code, you should be able to call `finish()` on the feed activity directly to dismiss it.

**Comment by ishaq-aym** [comment] 2019-02-20 06:41
@Bucimis i added this custom function on appBoyReactBridge.m file 
![image](https://user-images.githubusercontent.com/46740307/53071489-36f9e980-3504-11e9-89e7-144e6c61922e.png)
and then call this function on my js side like ReactAppboy.closeNewsFeedModal() . it works fine but i need to confirm with you that it's ok or not?

**Comment by Bucimis** [comment] 2019-02-20 21:59
@ishaq-aym looks reasonable to me!

**Comment by ishaq-aym** [comment] 2019-02-21 05:33
Thank you @Bucimis
