### ISSUE TITLE
News Feed counts, indicators, and OS

### ISSUE THREAD

**Issue by zevmo** [Appboy/appboy-react-sdk#11] opened 2017-03-14 12:39 UTC
We are trying to implement the News Feed as a source of updates and promotions, but finding it exceedingly difficult in the current version. 

- We are not getting (or able to get) the counts for unread messages.
- Only in Android does the unread indicator show and reset after opening the News Feed, iOS is always in a 'read' state.
- No ability for `requestFeedRefresh` for iOS in RN — or at least upgrade the iOS SDK
- No getUnreadCardCountForCategories to do a refresh in the background

Help!

**Comment by tiffanylu** [comment] 2017-03-14 16:22
Hi @zevmo,

Our sample application demonstrates working functionality for [getting the unread card count](https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/AppboyProject.js#L66) and [viewing the News Feed](https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/AppboyProject.js#L187). I am unable to reproduce your first two issues in our sample project; is there anything about your integration that might differ from ours? If so, would you be able to share a sample project that reproduces those two issues? (If it can't be shared publicly, you can also send the project to support@appboy.com.)

For requesting a News Feed refresh, could you please clarify what you mean by upgrading the iOS SDK? We'll look into adding `requestFeedRefresh()` in our next release, which should address your last two issues. We're hoping to release sometime in the next 6 weeks—please let us know if that solution and timeline work for you.

Best,
Tiff

**Comment by zevmo** [comment] 2017-03-14 17:53
Thanks for the info. 

A couple of clarifications:
- The iOS SDK that it uses is 2.24 but version 2.27 is out.
- The reset or read/unread only occurs if the app itself is restarted

**Comment by tiffanylu** [comment] 2017-03-14 20:59
Hi @zevmo,

Our React Native bridge does not ship with a set version of the iOS SDK. If you integrated the iOS SDK via Cocoapods, you can run `pod update` from the root of your iOS project to update to the latest version of the iOS SDK. 

The read and unread card counts are updated every time a Feed Updated Event happens. Currently, Feed Updated Events occur on session starts, calls to `changeUser()`, and when the user opens the News Feed and pulls down to refresh. 

Currently, `getReadCardCountForCategories()` and `getUnreadCardCountForCategories()` return cached card counts from the last Feed Updated Event. In addition to adding a `requestFeedRefresh()` method in our next release to force a News Feed refresh, we'll also look into updating our `getReadCardCountForCategories()` and `getUnreadCardCountForCategories()` implementations to return up-to-date card counts. Does this sound like it would address your use case?

Best,
Tiff

**Comment by zevmo** [comment] 2017-03-14 22:24
Hey @tiffanylu, 

That would work. I look forward to the update!

Thanks!
Z

**Comment by tiffanylu** [comment] 2017-04-04 00:23
Hi @zevmo,

Per https://github.com/Appboy/appboy-react-sdk/pull/12, you can now call `ReactAppboy.requestFeedRefresh()` to request a News Feed refresh from the server. This will ensure that any subsequent calls to `getCardCountForCategories()` or `getUnreadCardCountForCategories()` will have the most updated card counts from Appboy's servers. Note that both getCardCount methods continue to return the most up-to-date counts for the News Feed cards currently on the device.

Please let us know if this satisfies all of the points you raised, and if we can close out this issue. Thanks!

Best,
Tiff

**Comment by tiffanylu** [comment] 2017-04-11 15:27
Hey @zevmo! Have you gotten a chance to try out the solution above? 

Best,
Tiff

**Comment by tiffanylu** [comment] 2017-04-25 18:03
Hi @zevmo,

We've released v1.3.0 with official support for `requestFeedRefresh()`. I'm going to close this issue for now, but please feel free to reopen if v1.3.0 does not solve your use case.

Best,
Tiff

**Closed by tiffanylu** 2017-04-25 18:03 UTC

**Comment by gaceredo** [comment] 2018-08-10 13:39
Which method marks all the News Feed as read? Thank you

**Comment by Bucimis** [comment] 2018-08-10 18:33
Hi @gaceredo, there's currently no way to programmatically mark all cards as read through our React Native API. Cards are marked as read automatically as users navigate through the feed. 

Note that if you're manually displaying the feed with a custom UI, you may mark individual `Card` model objects as read as users navigate through your custom UI, but you'll need to do that through native Android/iOS code.
